Build fixes
Use casts to or from `uintptr_t' to avoid warnings on 32-bit platforms when we
get or set the FUSE private data in mount.c.

Make the XATTR interface optional.  Support is omitted automatically if the
setxattr() function or the `attr/xattr.h' header is not found.

Fix a couple of the test cases.

diff --git a/tests/test-imagex b/tests/test-imagex
--- a/tests/test-imagex
+++ b/tests/test-imagex
@@ -260,12 +260,14 @@ echo "Testing appending non-existent file (should generate errors)"
 if imagex append SOME_NONEXISTENT_FILE dir.wim; then
 	error "Incorrectly succeeded to append non-existent file to WIM"
 fi
-echo "Testing appending directory containing unreadable file (should generate errors)"
-mkdir -p dir3
-echo 1 > dir3/file
-chmod -r dir3/file
-if imagex append dir3 dir.wim; then
-	error "Incorrectly succeeded in capturing directory with unreadable file"
+if [ `id -u` != 0 ]; then
+	echo "Testing appending directory containing unreadable file (should generate errors)"
+	mkdir -p dir3
+	echo 1 > dir3/file
+	chmod -r dir3/file
+	if imagex append dir3 dir.wim; then
+		error "Incorrectly succeeded in capturing directory with unreadable file"
+	fi
 fi
 rm -rf dir3 dir.wim
 
@@ -361,7 +363,7 @@ fi
 if test "`stat -c %i tmp/subdir/hello`" = "`stat -c %i tmp/subdir/hello2`"; then
 	error "Incorrect inode number"
 fi
-if ! test -L tmp/subdir/hello || ! test -L tmp/subdir/hello2; then
+if ! test -L tmp/subdir/hello -o -L tmp/subdir/hello2 -o -L tmp/subdir/hellolink; then
 	error "Expected symlinks, but found non-symlinks"
 fi
 rm -rf dir.wim tmp
